### ISSUE TITLE
Economics crash with P_none

### ISSUE THREAD

**Issue by tbarchyn** [IM3S/LDAR_Sim#137]
`ldar_sim_main.py ./simulations/G_.yaml ./simulations/P_none.yaml`

Crashes in economics plotting section - perhaps better validation is needed to avoid doing economics calcs with just P_none.yaml?

Runs fine when adding another program to the mix.

```
Traceback (most recent call last):
  File "C:\Users\tom\.virtualenvs\src-9RtAWWXW\lib\site-packages\pandas\core\indexes\range.py", line 351, in get_loc
    return self._range.index(new_key)
ValueError: 1 is not in range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:/dev/LDAR_Sim_2/LDAR_Sim/src/ldar_sim_main.py", line 153, in <module>
    cost_mitigation = cost_mitigation(res, ref_program, no_program, output_directory)
  File "D:\dev\LDAR_Sim_2\LDAR_Sim\src\economics\cost_mitigation.py", line 121, in cost_mitigation
    plt.axhline(y=economics_df['carbon_price_tonnesCO2e'][1],
  File "C:\Users\tom\.virtualenvs\src-9RtAWWXW\lib\site-packages\pandas\core\series.py", line 824, in __getitem__
    return self._get_value(key)
  File "C:\Users\tom\.virtualenvs\src-9RtAWWXW\lib\site-packages\pandas\core\series.py", line 932, in _get_value
    loc = self.index.get_loc(label)
  File "C:\Users\tom\.virtualenvs\src-9RtAWWXW\lib\site-packages\pandas\core\indexes\range.py", line 353, in get_loc
    raise KeyError(key) from err
KeyError: 1
```

**Comment by c-vollrath** [comment]
Also resolved.
